### ISSUE TITLE
Publish online preview

### ISSUE THREAD

**Issue by johnsardine** [remoteoss/react-url-modal#11]
Hi @SaraVieira, amazing initiative. We're happy to help by publishing a live example in our Vercel account, what do you think?

**Comment by SaraVieira** [comment]
Yes pls!! It's just publishing the example  folder :)

**Comment by johnsardine** [comment]
@SaraVieira Cool, are you able to grant me permissions in the remoteoss org or this repo so I can set it up? Thank you

**Comment by SaraVieira** [comment]
Done! Sorry i don't know how to add everyone by default :/

**Comment by johnsardine** [comment]
Thank you, it worked. Now I just need the account owner to approve Vercel and then we can publish

**Comment by johnsardine** [comment]
@SaraVieira Here you have it https://react-url-modal.vercel.app/

**Comment by SaraVieira** [comment]
Thank you!!
