### ISSUE TITLE
Modal does not close on Vercel App

### ISSUE THREAD

**Issue by sdivelbiss** [remoteoss/react-url-modal#20]
When using the 'Using our Modal Component' when the Modal is open, it cannot be closed.

Steps to reproduce:
1. Navigate to [https://react-url-modal.vercel.app/](https://react-url-modal.vercel.app/)
2. Click on `Using our Modal Component`
3. Click on `Open Modal` to open the modal
4. Try to exit the modal

Expected:
User can open and close modal

**Comment by SaraVieira** [comment]
Done! It had been because I was cleaning some props and forgot to update the modal here
