### ISSUE TITLE
next/router is imported but could not be resolved error

### ISSUE THREAD

**Issue by brenelz** [remoteoss/react-url-modal#26]
When running `yarn dev` in the example folder i get this error unless I install next.

```
$ vite --port 3002
error when starting dev server:
Error: The following dependencies are imported but could not be resolved:

  next/router (imported by /Users/brenelz/Desktop/Code/react-url-modal/dist/react-url-modal.esm.js)
```

**Comment by SaraVieira** [comment]
Hey

Can you send me all the commands you did?

I had the same error yesterday but ever since I did [this commit](https://github.com/remoteoss/react-url-modal/commit/3b7817f7d13b76d8de66e2edce567d0b16190e17) it stopped happening to me

**Comment by brenelz** [comment]
I followed the readme. I think maybe it only happens with a fresh clone.

```
 git clone git@github.com:remoteoss/react-url-modal.git
cd react-url-modal
yarn
yarn dev
cd example
yarn && yarn dev (error here)
```

**Comment by SaraVieira** [comment]
Oh, i ran yarn build on the main folder

Let me try with yarn dev

**Comment by davidkiss96** [comment]
I am having the error issue:
next/router (imported by /.../react-url-modal/dist/react-url-modal.esm.js)

I am trying to use the package in my project, and it gives me the error. Since it is a regular react project not a next js project I do not have any intention installing it.
Any solution?

**Comment by maylortaylor** [comment]
> I am having the same error: next/router (imported by /.../react-url-modal/dist/react-url-modal.esm.js)
> 
> I am trying to use the package in my project, and it gives me the error. Since it is a regular react project not a next js project I do not have any intention installing it. Any solution?

Same exact thing is happening for me

`
ERROR in ./node_modules/react-url-modal/dist/react-url-modal.cjs.js 1:3035-3057
Module not found: Error: Can't resolve 'next/router' in '/Users/matttaylor/Documents/_dev/amver-ui/node_modules/react-url-modal/dist'
ERROR in ./node_modules/react-url-modal/dist/react-url-modal.cjs.js 1:3035-3057
Module not found: Error: Can't resolve 'next/router' in '/Users/matttaylor/Documents/_dev/amver-ui/node_modules/react-url-modal/dist'
`

**Comment by jfranciscosousa** [comment]
We are working on an update to completely remove the peer dependency on Next.js, that will solve the issue.

**Comment by pauleanbro** [comment]
any updates on the pr?

**Comment by brenelz** [comment]
I don't think anything more is happening on this repo
