### ISSUE TITLE
Responsive bug in some screen sizes

### ISSUE THREAD

**Issue by thien-do** [remoteoss/react-url-modal#28]
Hi team, looks like the website doesn't look good from 600px to 1440px. There are some common devices with these screen widths (tablets' are around 600 to 800 in portrait, 800 to 1200 in landscape, many laptops are around 1200 -> 1400)

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/5953369/159122695-00f79991-6bd7-422c-87ed-2a12a21ef0df.png">

Are you open for a PR to fix this?

**Comment by SaraVieira** [comment]
Hey!

That would be amazing!

**Comment by thien-do** [comment]
Wow thanks @arjunan-k @jfranciscosousa !
