### ISSUE TITLE
`params` prop is null when opening a modal from another modal

### ISSUE THREAD

**Issue by ivan-herrero** [remoteoss/react-url-modal#29]
# Description

Under certain scenarios, when opening a modal when another modal is already opened, the `params` prop is unexpectedly `null`, which can lead to the infamous "cannot read properties of null/undefined" error.

I'm not entirely sure what's the root cause.

It might be related to the `params` query param in the URL not being synced with the modal that is already opened/closed, so the `getData()` function in `src/URLModal.tsx` returns `null`.

# Solution (unknown)

A (partial) workaround could be to change line `129` in `src/URLModal.tsx` to:
```
params={getData() || {}}
```

This would avoid users from having to null-check the `params` prop, but they would still need to null check every property inside `params`, which is not ideal.

# Steps to reproduce

- Clone https://github.com/ivan-herrero/react-url-modal/tree/bug/params-is-null
- Install dependencies and run the example app
- Click on "Open 1st modal"
- Click on "Open 2nd modal"
- Click on "Open 1st modal" again
- App errors with `Uncaught TypeError: Cannot read properties of undefined (reading 'stuff')`

**Comment by jfranciscosousa** [comment]
Fixed by #30
