### ISSUE TITLE
Remove `atob` and `btoa` as they deprecated

### ISSUE THREAD

**Issue by SaraVieira** [remoteoss/react-url-modal#3]
https://github.com/remoteoss/react-url-modal/blob/18dd4943ef3a8f468f6ae0365a9406900a22da35/src/index.tsx#L28-L37

```
// Deprecated
btoa(string)

// Buffer equivalent
Buffer.from(string).toString('base64')
```

```
// deprecated
atob(string)
// Buffer equivalent - not so sure about this one
new Buffer(str, 'base64').toString('binary');
```

**Comment by jfranciscosousa** [comment]
https://github.com/microsoft/TypeScript/issues/45566

That warning is just for `node.js` I believe.

No warnings on MDN at least 😂 https://developer.mozilla.org/en-US/docs/Web/API/btoa

**Comment by SaraVieira** [comment]
Better even! Closing this
